# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\dev\tools\CMake\bin\cmake.exe

# The command to remove a file.
RM = C:\dev\tools\CMake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\dev\sdlgl3-wavefront-trunk

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\dev\sdlgl3-wavefront-trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\dev\tools\CMake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\dev\tools\CMake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\dev\sdlgl3-wavefront-trunk\CMakeFiles C:\dev\sdlgl3-wavefront-trunk\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\dev\sdlgl3-wavefront-trunk\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sdlglapp

# Build rule for target.
sdlglapp: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sdlglapp
.PHONY : sdlglapp

# fast build rule for target.
sdlglapp/fast:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/build
.PHONY : sdlglapp/fast

dependencies/tinyobjloader/tiny_obj_loader.obj: dependencies/tinyobjloader/tiny_obj_loader.cc.obj
.PHONY : dependencies/tinyobjloader/tiny_obj_loader.obj

# target to build an object file
dependencies/tinyobjloader/tiny_obj_loader.cc.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/dependencies/tinyobjloader/tiny_obj_loader.cc.obj
.PHONY : dependencies/tinyobjloader/tiny_obj_loader.cc.obj

dependencies/tinyobjloader/tiny_obj_loader.i: dependencies/tinyobjloader/tiny_obj_loader.cc.i
.PHONY : dependencies/tinyobjloader/tiny_obj_loader.i

# target to preprocess a source file
dependencies/tinyobjloader/tiny_obj_loader.cc.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/dependencies/tinyobjloader/tiny_obj_loader.cc.i
.PHONY : dependencies/tinyobjloader/tiny_obj_loader.cc.i

dependencies/tinyobjloader/tiny_obj_loader.s: dependencies/tinyobjloader/tiny_obj_loader.cc.s
.PHONY : dependencies/tinyobjloader/tiny_obj_loader.s

# target to generate assembly for a file
dependencies/tinyobjloader/tiny_obj_loader.cc.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/dependencies/tinyobjloader/tiny_obj_loader.cc.s
.PHONY : dependencies/tinyobjloader/tiny_obj_loader.cc.s

src/BinaryData.obj: src/BinaryData.cpp.obj
.PHONY : src/BinaryData.obj

# target to build an object file
src/BinaryData.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/BinaryData.cpp.obj
.PHONY : src/BinaryData.cpp.obj

src/BinaryData.i: src/BinaryData.cpp.i
.PHONY : src/BinaryData.i

# target to preprocess a source file
src/BinaryData.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/BinaryData.cpp.i
.PHONY : src/BinaryData.cpp.i

src/BinaryData.s: src/BinaryData.cpp.s
.PHONY : src/BinaryData.s

# target to generate assembly for a file
src/BinaryData.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/BinaryData.cpp.s
.PHONY : src/BinaryData.cpp.s

src/Camera.obj: src/Camera.cpp.obj
.PHONY : src/Camera.obj

# target to build an object file
src/Camera.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Camera.cpp.obj
.PHONY : src/Camera.cpp.obj

src/Camera.i: src/Camera.cpp.i
.PHONY : src/Camera.i

# target to preprocess a source file
src/Camera.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Camera.cpp.i
.PHONY : src/Camera.cpp.i

src/Camera.s: src/Camera.cpp.s
.PHONY : src/Camera.s

# target to generate assembly for a file
src/Camera.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Camera.cpp.s
.PHONY : src/Camera.cpp.s

src/Frustum.obj: src/Frustum.cpp.obj
.PHONY : src/Frustum.obj

# target to build an object file
src/Frustum.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Frustum.cpp.obj
.PHONY : src/Frustum.cpp.obj

src/Frustum.i: src/Frustum.cpp.i
.PHONY : src/Frustum.i

# target to preprocess a source file
src/Frustum.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Frustum.cpp.i
.PHONY : src/Frustum.cpp.i

src/Frustum.s: src/Frustum.cpp.s
.PHONY : src/Frustum.s

# target to generate assembly for a file
src/Frustum.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Frustum.cpp.s
.PHONY : src/Frustum.cpp.s

src/GpuProgram.obj: src/GpuProgram.cpp.obj
.PHONY : src/GpuProgram.obj

# target to build an object file
src/GpuProgram.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/GpuProgram.cpp.obj
.PHONY : src/GpuProgram.cpp.obj

src/GpuProgram.i: src/GpuProgram.cpp.i
.PHONY : src/GpuProgram.i

# target to preprocess a source file
src/GpuProgram.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/GpuProgram.cpp.i
.PHONY : src/GpuProgram.cpp.i

src/GpuProgram.s: src/GpuProgram.cpp.s
.PHONY : src/GpuProgram.s

# target to generate assembly for a file
src/GpuProgram.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/GpuProgram.cpp.s
.PHONY : src/GpuProgram.cpp.s

src/Material.obj: src/Material.cpp.obj
.PHONY : src/Material.obj

# target to build an object file
src/Material.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Material.cpp.obj
.PHONY : src/Material.cpp.obj

src/Material.i: src/Material.cpp.i
.PHONY : src/Material.i

# target to preprocess a source file
src/Material.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Material.cpp.i
.PHONY : src/Material.cpp.i

src/Material.s: src/Material.cpp.s
.PHONY : src/Material.s

# target to generate assembly for a file
src/Material.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Material.cpp.s
.PHONY : src/Material.cpp.s

src/Renderer.obj: src/Renderer.cpp.obj
.PHONY : src/Renderer.obj

# target to build an object file
src/Renderer.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Renderer.cpp.obj
.PHONY : src/Renderer.cpp.obj

src/Renderer.i: src/Renderer.cpp.i
.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s
.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/SceneNode.obj: src/SceneNode.cpp.obj
.PHONY : src/SceneNode.obj

# target to build an object file
src/SceneNode.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/SceneNode.cpp.obj
.PHONY : src/SceneNode.cpp.obj

src/SceneNode.i: src/SceneNode.cpp.i
.PHONY : src/SceneNode.i

# target to preprocess a source file
src/SceneNode.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/SceneNode.cpp.i
.PHONY : src/SceneNode.cpp.i

src/SceneNode.s: src/SceneNode.cpp.s
.PHONY : src/SceneNode.s

# target to generate assembly for a file
src/SceneNode.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/SceneNode.cpp.s
.PHONY : src/SceneNode.cpp.s

src/Shader.obj: src/Shader.cpp.obj
.PHONY : src/Shader.obj

# target to build an object file
src/Shader.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Shader.cpp.obj
.PHONY : src/Shader.cpp.obj

src/Shader.i: src/Shader.cpp.i
.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s
.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/Terrain.obj: src/Terrain.cpp.obj
.PHONY : src/Terrain.obj

# target to build an object file
src/Terrain.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Terrain.cpp.obj
.PHONY : src/Terrain.cpp.obj

src/Terrain.i: src/Terrain.cpp.i
.PHONY : src/Terrain.i

# target to preprocess a source file
src/Terrain.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Terrain.cpp.i
.PHONY : src/Terrain.cpp.i

src/Terrain.s: src/Terrain.cpp.s
.PHONY : src/Terrain.s

# target to generate assembly for a file
src/Terrain.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Terrain.cpp.s
.PHONY : src/Terrain.cpp.s

src/Texture.obj: src/Texture.cpp.obj
.PHONY : src/Texture.obj

# target to build an object file
src/Texture.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Texture.cpp.obj
.PHONY : src/Texture.cpp.obj

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles\sdlglapp.dir\build.make CMakeFiles/sdlglapp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... sdlglapp
	@echo ... dependencies/tinyobjloader/tiny_obj_loader.obj
	@echo ... dependencies/tinyobjloader/tiny_obj_loader.i
	@echo ... dependencies/tinyobjloader/tiny_obj_loader.s
	@echo ... src/BinaryData.obj
	@echo ... src/BinaryData.i
	@echo ... src/BinaryData.s
	@echo ... src/Camera.obj
	@echo ... src/Camera.i
	@echo ... src/Camera.s
	@echo ... src/Frustum.obj
	@echo ... src/Frustum.i
	@echo ... src/Frustum.s
	@echo ... src/GpuProgram.obj
	@echo ... src/GpuProgram.i
	@echo ... src/GpuProgram.s
	@echo ... src/Material.obj
	@echo ... src/Material.i
	@echo ... src/Material.s
	@echo ... src/Renderer.obj
	@echo ... src/Renderer.i
	@echo ... src/Renderer.s
	@echo ... src/SceneNode.obj
	@echo ... src/SceneNode.i
	@echo ... src/SceneNode.s
	@echo ... src/Shader.obj
	@echo ... src/Shader.i
	@echo ... src/Shader.s
	@echo ... src/Terrain.obj
	@echo ... src/Terrain.i
	@echo ... src/Terrain.s
	@echo ... src/Texture.obj
	@echo ... src/Texture.i
	@echo ... src/Texture.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

